#!/bin/bash

DEVD="$HOME/Dev"
AGGD="$DEVD/agg3/agg3.0"
CMGD="$DEVD/commitmentmanager"
MMID="$DEVD/market-maker-inbox"
NTSD="$HOME/Dropbox/Notes"

tmux start-server
tmux new-session -d -s work

tmux new-window   -c $AGGD -n agg  -t work:1
tmux split-window -c $AGGD -p 25   -t work:1
tmux split-window -c $AGGD -h      -t work:1.1
tmux send-keys -t work:1.0 Enter "vim ." Enter
tmux send-keys -t work:1.2 "node" Enter

tmux new-window   -c $CMGD -n cmgr -t work:2
tmux split-window -c $CMGD -p 25   -t work:2
tmux split-window -c $CMGD -h      -t work:2.1
tmux send-keys -t work:2.0 "vim ." Enter
tmux send-keys -t work:2.1 "git status" Enter
tmux send-keys -t work:2.2 "direnv reload ; bundle exec rails c" Enter

tmux new-window   -c $MMID -n mmi  -t work:3
tmux split-window -c $MMID -p 25   -t work:3
tmux split-window -c $MMID -h      -t work:3.1
tmux send-keys -t work:3.0 "vim ." Enter
tmux send-keys -t work:3.1 "git status" Enter
tmux send-keys -t work:3.2 "direnv reload ; bundle exec rails c" Enter

tmux new-window   -c $NTSD -n note -t work:4
tmux split-window -c $NTSD -p 25   -t work:4
tmux send-keys -t work:4.0 "vim ." Enter

tmux -2 attach-session -t work:0
